### ISSUE TITLE
Scope.GUILDS 

### ISSUE THREAD

**Issue by zerefdev** [oauth-everything/passport-discord#5]
Scope.GUILDS is not being returned.

**Comment by vickylance** [comment]
I am blocked because of this hence going back to the passport-discord npm package

**Comment by Tschrock** [comment]
From my testing, Scope.GUILDS is being passed to the Oauth request like it's supposed to be, so I don't consider this a bug. It's important to note that neither this library nor `passport-discord` are API Libraries, they are OAuth Strategies.

While `passport-discord` does do some extra shenanigans to jerry-rig guild/connection information into their profile data, if you really want to interact with the Discord API you should use an API Library or make the API requests yourself using the `accessToken` that is returned from the Oauth request.
